# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title approx_fpop
#'
#' @description Detection changepoints using the Functional Pruning Optimal Partitioning method (FPOP) in p-variate time series in a p-variable time series of length n.
#'
#' @param data is a matrix of data(p-rows x n-columns).
#' @param penalty is a value of penalty (a non-negative real number).
#' @param type_approx is a value defining the  type of geometry for FPOP-pruning: type=1: ("intersection" of sets), approximation - rectangle; type=2:("intersection" of sets)"minus"("union" of sets), approximation - rectangle; type=3: (last disk)"minus"("union" of sets), approximation - disk.
#'
#' @return a list of  elements  = (changepoints, means, globalCost).
#'
#' \describe{
#' \item{\code{chpts}}{is the changepoint vector that gives the last index of each segment for the p-variate time series.}
#' \item{\code{means}}{is the list of successive means for the p-variate time series.}
#' \item{\code{globalCost}}{is a number equal to the global cost.}
#' }
#'
#' @examples approx_fpop(data = chpt_rnorm(p = 3, n = 100, chpts = 50, means = matrix(c (1,2,3,4, 5, 7), nrow = 3), noise = 1), penalty = 2*log(100), type_approx = 2)
#' data2 =  chpt_rnorm(p = 2, n = 100, chpts = 50, means = matrix(c(0,10,1,10), nrow = 2), noise = 1)
#'approx_fpop(data2, penalty = 2*log(100), type_approx = 2)
#'approx_fpop(data = chpt_rnorm(p = 2, n = 100, chpts = 50, means = matrix(c (1,2,7,9), nrow = 2), noise = 1), penalty = 2*log(100), type_approx = 2)
approx_fpop <- function(data, penalty, type_approx) {
    .Call(`_FPOPapproximation_approx_fpop`, data, penalty, type_approx)
}

