# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title approx_fpop
#'
#' @description FPOP method (using the rectangle approximation of the sets) for  the multiple changepoint detection.
#' @param data is a matrix of data (p-rows x n-columns).
#' @param penalty is a value of penalty (a non-negative real number).
#' @param intersection is the type of intersection : 'empty', 'all', 'last', 'random' or 'sphere'.
#' @param exclusion is the type of intersection : 'empty', 'all', 'random' or 'sphere'.
#' The following parameter combinations are implemented:
#' (intersection ='sphere', exclusion ='sphere')
#' (intersection ='all', exclusion ='all')
#' (intersection ='all', exclusion ='empty')
#' (intersection ='empty', exclusion ='all')
#' (intersection ='last', exclusion ='all')
#' (intersection ='last', exclusion ='random')
#' (intersection ='all', exclusion ='random')
#' (intersection ='random', exclusion ='random')
#' (intersection ='empty', exclusion ='empty')
#' @param NbOfCands is the logical parameter (if NbOfCands = TRUE, than the file "NbOfCands.txt" contains the number of change candidates for each iteration.
#' @param NbOfExclus is the logical parameter (if NbOfExclus = TRUE, than the file "NbOfExclus.txt" contains the label of candidate and the number of exclusion for change candidates for each iteration.
#'
#' @return a list of  elements  = (changes, means, globalCost).
#'
#' \describe{
#' \item{\code{changes}}{is the changepoint vector that gives the last index of each segment for the p-variate time series.}
#' \item{\code{means}}{is the list of successive means for the p-variate time series.}
#' \item{\code{globalCost}}{is a number equal to the global cost.}
#' }
#'
#' @examples approx_fpop(data = chpt_rnorm(p = 3, n = 100, changes = 50, means = matrix(c (1,2,3,4, 5, 7), nrow = 3), noise = 1), penalty = 2*log(100), type_approx = 2)
#' N <- 11
#' Chpt <-5
#' Means <-  matrix(c(0,1,1,10time_series <- changes_rnorm(p = Dim, n = N, changes = Chpt, means = Means, noise = Noise)), nrow = 2)
#' Noise <- 1
#' Dim <- 2
#' Penality <- 2*Dim*log(N)
#' time_series <- changes_rnorm(p = Dim, n = N, changes = Chpt, means = Means, noise = Noise)
#'Approx <- list()
#'Approx[[1]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'sphere', exclusion = 'sphere', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[2]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'all', exclusion = 'all', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[3]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'all', exclusion = 'empty', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[4]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'empty', exclusion = 'all', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[5]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'last', exclusion = 'all', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[6]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'last', exclusion = 'random', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[7]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'all', exclusion = 'random', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[8]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'random', exclusion = 'random', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx[[9]] <- approx_fpop(data = time_series, penalty = Penality, intersection = 'empty', exclusion = 'empty', NbOfCands = FALSE, NbOfExclus = FALSE)
#'Approx
approx_fpop <- function(data, penalty, intersection = "all", exclusion = "all", NbOfCands = FALSE, NbOfExclus = FALSE) {
    .Call(`_FPOPapproximation_approx_fpop`, data, penalty, intersection, exclusion, NbOfCands, NbOfExclus)
}

